### ISSUE TITLE
Error with `const_get': uninitialized constant Patches::IssuePatch (NameError)

### ISSUE THREAD

**Issue by gmasny** [conveniencable/microsoft_project_connector#21]
HI! I want install plugin for my redmine. And i have problem with it.

```
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/helpers.rb:137:in `const_get': uninitialized constant Patches::IssuePatch (NameError)
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/helpers.rb:137:in `cget'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/eager_load.rb:175:in `block in actual_eager_load_dir'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/helpers.rb:42:in `block in ls'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/helpers.rb:27:in `each'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/helpers.rb:27:in `ls'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/eager_load.rb:16:in `each'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader.rb:377:in `block in eager_load_all'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader.rb:375:in `each'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.10/lib/zeitwerk/loader.rb:375:in `eager_load_all'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.7.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.7.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
	from /home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
	from config.ru:4:in `require'
	from config.ru:4:in `block in <main>'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/builder.rb:125:in `instance_eval'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/rack-2.2.8/lib/rack/builder.rb:125:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/unicorn-5.8.0/lib/unicorn.rb:54:in `eval'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/unicorn-5.8.0/lib/unicorn.rb:54:in `block in builder'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/unicorn-5.8.0/bin/unicorn_rails:139:in `block in rails_builder'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/unicorn-5.8.0/lib/unicorn/http_server.rb:826:in `build_app!'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/unicorn-5.8.0/lib/unicorn/http_server.rb:141:in `start'
	from /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/unicorn-5.8.0/bin/unicorn_rails:209:in `<top (required)>'
	from /home/redmine/redmine/vendor/bundle/ruby/2.7.0/bin/unicorn_rails:23:in `load'
	from /home/redmine/redmine/vendor/bundle/ruby/2.7.0/bin/unicorn_rails:23:in `<main>'
I, [2023-08-01T13:36:11.074170 #324]  INFO -- : Refreshing Gem list
I, [2023-08-01T13:36:14.963799 #324]  INFO -- : listening on addr=/home/redmine/redmine/tmp/sockets/redmine.socket fd=7
I, [2023-08-01T13:36:14.964016 #324]  INFO -- : listening on addr=127.0.0.1:8080 fd=9
I, [2023-08-01T13:36:14.999655 #324]  INFO -- : master process ready
I, [2023-08-01T13:36:15.076602 #329]  INFO -- : worker=0 ready
I, [2023-08-01T13:36:15.076690 #331]  INFO -- : worker=1 ready
I, [2023-08-01T13:38:48.377549 #324]  INFO -- : reaped #<Process::Status: pid 329 exit 0> worker=0
I, [2023-08-01T13:38:48.377678 #324]  INFO -- : reaped #<Process::Status: pid 331 exit 0> worker=1
I, [2023-08-01T13:38:48.377758 #324]  INFO -- : master complete
I, [2023-08-01T13:38:52.320636 #270]  INFO -- : Refreshing Gem list
I, [2023-08-01T13:38:56.227396 #270]  INFO -- : listening on addr=/home/redmine/redmine/tmp/sockets/redmine.socket fd=7
I, [2023-08-01T13:38:56.227608 #270]  INFO -- : listening on addr=127.0.0.1:8080 fd=9
I, [2023-08-01T13:38:56.295092 #275]  INFO -- : worker=0 ready
I, [2023-08-01T13:38:56.301657 #270]  INFO -- : master process ready
I, [2023-08-01T13:38:56.380129 #277]  INFO -- : worker=1 ready
```
My env:
docker-redmine 5.0.4
Environment:
  Redmine version                5.0.4.stable
  Ruby version                   2.7.5-p203 (2021-11-24) [x86_64-linux-gnu]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Classic
SCM:
  Subversion                     1.13.0
  Mercurial                      5.3.1
  Cvs                            1.12.13
  Bazaar                         3.0.2
  Git                            2.41.0
  Filesystem                     
Redmine plugins:
  no plugin installed
  
  Can you help me?

**Comment by conveniencable** [comment]
It is a zeitwerk problem. Please update the redmine plugin to 1.0.15.

**Comment by conveniencable** [comment]
Can you try redmine 5.0.5.stable? It works on my window 10 WSL.
